# Generated by Django 5.1.6 on 2026-05-04 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text='OpenRouter model ID e.g. "openai/gpt-4o-mini"', max_length=150, unique=True)),
                ('credits_per_1k_input', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('credits_per_1k_output', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Model Pricing',
                'verbose_name_plural': 'Model Pricing',
                'ordering': ['model_id'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('monthly_credits', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('max_messages_per_month', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('allowed_models', models.JSONField(blank=True, default=list, help_text='e.g. ["openai/gpt-4o-mini"]')),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price_per_month'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Negative = debit, positive = credit', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('deduction', 'Deduction'), ('renewal', 'Renewal'), ('top_up', 'Top-up'), ('adjustment', 'Manual Adjustment'), ('plan_change', 'Plan Change')], max_length=20)),
                ('reply_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_remaining', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('credits_total', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('messages_used', models.IntegerField(default=0)),
                ('renewal_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Balance',
                'verbose_name_plural': 'User Balances',
            },
        ),
        migrations.CreateModel(
            name='UsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_replies', models.IntegerField(default=0)),
                ('total_ai_calls', models.IntegerField(default=0)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_credits_used', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Summary',
                'verbose_name_plural': 'Usage Summaries',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
