# Generated by Django 5.1.6 on 2026-05-04 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assistant', max_length=100)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('friendly', 'Friendly'), ('professional', 'Professional'), ('casual', 'Casual'), ('humorous', 'Humorous')], default='friendly', max_length=20)),
                ('style', models.CharField(choices=[('concise', 'Concise'), ('detailed', 'Detailed'), ('conversational', 'Conversational'), ('formal', 'Formal')], default='conversational', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('fr', 'French'), ('es', 'Spanish'), ('tr', 'Turkish'), ('id', 'Indonesian')], default='en', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='agent_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Identity',
                'verbose_name_plural': 'Agent Identities',
            },
        ),
        migrations.CreateModel(
            name='BehaviorRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_message', models.TextField(blank=True, null=True)),
                ('out_of_hours_message', models.TextField(blank=True, null=True)),
                ('chit_chat_enabled', models.BooleanField(default=True)),
                ('chit_chat_style', models.CharField(choices=[('off', 'Off'), ('minimal', 'Minimal'), ('moderate', 'Moderate'), ('full', 'Full')], default='moderate', max_length=20)),
                ('cross_sell_enabled', models.BooleanField(default=True)),
                ('ask_open_ended', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Behavior Rules',
                'verbose_name_plural': 'Behavior Rules',
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_charge_inside', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charge_outside', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('support_open_time', models.TimeField(default='09:00')),
                ('support_close_time', models.TimeField(default='21:00')),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Config',
                'verbose_name_plural': 'Store Configs',
            },
        ),
    ]
