# Generated by Django 5.1.6 on 2026-05-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorrules',
            name='knowledge_base',
            field=models.TextField(blank=True, help_text="Facts the AI should always know. One per line. e.g. 'Return policy: 7 days, no questions asked.'"),
        ),
    ]
