# Generated by Django 5.1.6 on 2026-05-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_add_knowledge_base_to_behaviorrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorrules',
            name='sample_questions_answers',
            field=models.TextField(blank=True, help_text='Sample Q&A pairs for AI training (format: Q: question\\nA: answer)'),
        ),
    ]
