# Generated by Django 5.1.6 on 2026-06-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_add_sample_qa_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorrules',
            name='custom_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
