# Generated by Django 5.1.6 on 2026-06-12 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_behaviorrules_custom_instructions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The chunk text (e.g. a single Q&A pair)')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding as a list of floats', null=True)),
                ('source', models.CharField(choices=[('sample_qa', 'Sample Q&A'), ('knowledge_base', 'Knowledge Base')], default='sample_qa', max_length=50)),
                ('chunk_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG Chunk',
                'verbose_name_plural': 'RAG Chunks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'source', 'is_active'], name='context_rag_user_id_b79d57_idx')],
            },
        ),
    ]
