# Generated by Django 5.1.6 on 2026-07-30 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_alter_toolcalllog_fk'),
        ('context', '0005_ragchunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProactiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sync_failure', 'Sync Failure'), ('low_stock', 'Low Stock'), ('token_expiry', 'Token Expiry'), ('subscription_expiring', 'Subscription Expiring')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notify_channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('email', 'Email')], default='whatsapp', max_length=20)),
                ('threshold', models.JSONField(blank=True, default=dict, help_text='Rule-specific thresholds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proactive Rule',
                'verbose_name_plural': 'Proactive Rules',
            },
        ),
        migrations.CreateModel(
            name='SessionContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Idle — no active workflow'), ('browsing', 'Customer is browsing products'), ('product_selected', 'A specific product was selected'), ('awaiting_details', 'AI is collecting order details'), ('awaiting_confirmation', 'AI is waiting for order confirmation'), ('checkout', 'Checkout in progress'), ('payment', 'Payment flow active'), ('completed', 'Order/Workflow completed'), ('escalated', 'Handed off to human')], default='idle', max_length=30)),
                ('current_workflow', models.CharField(blank=True, default='', max_length=100)),
                ('workflow_step', models.IntegerField(default=0)),
                ('collected_data', models.JSONField(blank=True, default=dict)),
                ('pending_confirmation', models.JSONField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='back.conversation')),
            ],
            options={
                'verbose_name': 'Session Context',
                'verbose_name_plural': 'Session Contexts',
            },
        ),
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('preference', 'User Preference'), ('fact', 'Extracted Fact'), ('behavior', 'Behavior Pattern'), ('context', 'Business Context')], default='fact', max_length=20)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory Entry',
                'verbose_name_plural': 'Memory Entries',
                'indexes': [models.Index(fields=['user', 'memory_type', 'is_active'], name='context_mem_user_id_08220b_idx'), models.Index(fields=['user', 'key'], name='context_mem_user_id_d7c055_idx')],
            },
        ),
    ]
