# Generated by Django 5.1.6 on 2026-08-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0006_proactiverule_sessioncontext_memoryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncontext',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle — no active workflow'), ('browsing', 'Customer is browsing products'), ('product_selected', 'A specific product was selected'), ('awaiting_product_selection', 'AI asks which product to order'), ('awaiting_variation', 'AI asks which size/variant'), ('awaiting_details', 'AI is collecting order details'), ('awaiting_confirmation', 'AI is waiting for order confirmation'), ('checkout', 'Checkout in progress'), ('payment', 'Payment flow active'), ('completed', 'Order/Workflow completed'), ('escalated', 'Handed off to human')], default='idle', max_length=30),
        ),
    ]
