# Generated by Django 5.1.6 on 2026-08-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0007_alter_sessioncontext_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncontext',
            name='pre_collected',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
