# Generated by Django 5.1.6 on 2026-08-14 03:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0027_userprofile_setup_completed_at'),
        ('context', '0008_sessioncontext_pre_collected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('platform', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('lifecycle_stage', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('customer', 'Customer'), ('repeat_customer', 'Repeat Customer'), ('vip', 'VIP'), ('inactive', 'Inactive')], default='lead', max_length=20)),
                ('lead_score', models.IntegerField(default=0, help_text='0-100, derived from buying signals')),
                ('buying_probability', models.FloatField(default=0.0, help_text='0.0-1.0, derived')),
                ('facts', models.JSONField(blank=True, default=dict, help_text='{key: {value, source, confidence}}')),
                ('preferences', models.JSONField(blank=True, default=list, help_text='list of {pid, name, count}')),
                ('objections', models.JSONField(blank=True, default=list, help_text='list of {type, text, count}')),
                ('buying_signals', models.JSONField(blank=True, default=dict, help_text='boolean signal flags')),
                ('order_count', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('first_order_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to='back.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_customer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('discovery', 'Discovery'), ('product_interest', 'Product Interest'), ('considering', 'Considering'), ('ready_to_buy', 'Ready to Buy'), ('negotiating', 'Negotiating'), ('won', 'Won'), ('lost', 'Lost')], default='discovery', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=10)),
                ('intent', models.CharField(blank=True, default='', max_length=100)),
                ('current_product_pid', models.CharField(blank=True, default='', max_length=50)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buying_probability', models.FloatField(default=0.0, help_text='0.0-1.0, derived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_opportunity', to='back.conversation')),
                ('customer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='context.customerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Opportunity',
                'verbose_name_plural': 'Sales Opportunities',
            },
        ),
        migrations.CreateModel(
            name='OrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list, help_text='[{pid, name, qty, unit_price, variation_id}]')),
                ('delivery_zone', models.CharField(choices=[('inside_dhaka', 'Inside Dhaka'), ('outside_dhaka', 'Outside Dhaka')], default='inside_dhaka', max_length=20)),
                ('item_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confirmation_status', models.CharField(choices=[('no_order', 'No Order'), ('draft', 'Draft'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='no_order', max_length=24)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_order_draft', to='back.conversation')),
                ('converted_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_draft', to='back.sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_order_drafts', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_drafts', to='context.salesopportunity')),
            ],
            options={
                'verbose_name': 'Order Draft',
                'verbose_name_plural': 'Order Drafts',
            },
        ),
        migrations.CreateModel(
            name='CrmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stage_change', 'Stage Change'), ('order_draft', 'Order Draft'), ('order_created', 'Order Created'), ('fact_recorded', 'Fact Recorded'), ('ticket_created', 'Ticket Created'), ('signal', 'Signal'), ('lifecycle_change', 'Lifecycle Change'), ('note', 'Note')], default='note', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_events', to='back.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Event',
                'verbose_name_plural': 'CRM Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['conversation', '-timestamp'], name='context_crm_convers_4e87ee_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['user', 'lifecycle_stage'], name='context_cus_user_id_be1a52_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['user', 'phone'], name='context_cus_user_id_4dd70c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['user', '-last_contact_at'], name='context_cus_user_id_d1dba2_idx'),
        ),
        migrations.AddIndex(
            model_name='salesopportunity',
            index=models.Index(fields=['user', 'stage', 'status'], name='context_sal_user_id_080472_idx'),
        ),
        migrations.AddIndex(
            model_name='salesopportunity',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='context_sal_user_id_e174ca_idx'),
        ),
    ]
