# Generated by Django 5.2.7 on 2025-11-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('ecommerce', 'E-commerce'), ('service', 'Service Business'), ('local_shop', 'Local Shop'), ('b2b', 'Wholesale / B2B'), ('personal_brand', 'Personal Brand'), ('education', 'Education'), ('health_beauty', 'Health & Beauty'), ('saas', 'Startup / SaaS'), ('corporate', 'Corporate'), ('other', 'Other')], max_length=50)),
                ('customer_range', models.CharField(choices=[('1-5', '1-5'), ('5-10', '5-10'), ('10-50', '10-50'), ('50-100', '50-100'), ('100-500', '100-500'), ('500-1000', '500-1000')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('social_page', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
