# Generated by Django 5.2.7 on 2026-01-14 16:58

import django.db.models.deletion
import shortuuid.django_fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('messenger', 'Messenger'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=20)),
                ('customer_id', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20, null=True)),
                ('refer_customer_with', models.CharField(default='Sir', max_length=20)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('is_ai_enabled', models.BooleanField(default=True)),
                ('ai_disabled_at', models.DateTimeField(blank=True, null=True)),
                ('ai_enable_delay', models.IntegerField(default=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_summary', models.TextField(blank=True, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_returning', models.BooleanField(default=False)),
                ('preferred_tone', models.CharField(blank=True, max_length=50, null=True)),
                ('last_viewed_product', models.CharField(blank=True, max_length=255, null=True)),
                ('detected_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('current_product', models.CharField(blank=True, max_length=500, null=True)),
                ('language_detected', models.CharField(blank=True, max_length=20, null=True)),
                ('order_status', models.CharField(blank=True, max_length=100, null=True)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('missing_order_fields', models.JSONField(blank=True, null=True)),
                ('greeted', models.BooleanField(default=False)),
                ('image_allowed', models.BooleanField(default=True)),
                ('last_message_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_category', models.CharField(blank=True, max_length=100, null=True)),
                ('related_products', models.JSONField(blank=True, null=True)),
                ('interest_score', models.FloatField(blank=True, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bot_sent_count', models.IntegerField(default=0)),
                ('bot_received_count', models.IntegerField(default=0)),
                ('customer_sent_count', models.IntegerField(default=0)),
                ('agent_sent_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('messenger', 'Messenger'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], max_length=20)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('bot', 'Bot'), ('agent', 'Agent')], max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='back.conversation')),
                ('replied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='back.message', to_field='mid')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=6, max_length=15, prefix='pac_')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=100)),
                ('upsell_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='package.jpg', upload_to='package')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='package.jpg', upload_to='package-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.package')),
            ],
            options={
                'verbose_name_plural': 'Package Images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='product.jpg', upload_to='products')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('upsell_enabled', models.BooleanField(default=False)),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=6, max_length=15, prefix='sku_')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remove_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_default', models.BooleanField(default=True)),
                ('is_optional', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='back.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='product-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20)),
                ('delivered_to', models.CharField(choices=[('inside_dhaka', 'Inside Dhaka'), ('outside_dhaka', 'Outside Dhaka')], default='inside_dhaka', max_length=20)),
                ('updated_to_web', models.CharField(choices=[('failed', 'Failed'), ('updated', 'Updated')], default='failed', max_length=20)),
                ('external_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_address', models.CharField(blank=True, max_length=150)),
                ('customer_city', models.CharField(blank=True, max_length=150)),
                ('customer_state', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('customer_id', models.CharField(max_length=255)),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=6, max_length=15, prefix='ord_')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('delivering', 'Delivering'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package', to='back.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('base', 'Base Included'), ('added', 'Added'), ('removed', 'Removed')], default='base', max_length=20)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_name', models.CharField(blank=True, default='Unknown Product', max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('external_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_variation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_product_data', models.JSONField(blank=True, null=True)),
                ('internal_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='back.product')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='back.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='back.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('messenger', 'Messenger'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=20)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('ai_rules', models.JSONField(blank=True, default=dict)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('fallback_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('product_type', models.CharField(choices=[('normal_product', 'Normal Product'), ('digital', 'Digital Product'), ('package', 'Package'), ('reservation', 'Reservation'), ('service', 'Service')], default='normal_product', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user', 'platform', 'customer_id'), name='unique_user_platform_customer'),
        ),
    ]
