# Generated by Django 5.2.7 on 2026-01-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='current_package',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
