# Generated by Django 5.2.7 on 2026-01-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product_type',
            field=models.CharField(choices=[('normal_product', 'Normal Product'), ('digital', 'Digital Product'), ('package', 'Package'), ('reservation', 'Reservation'), ('service', 'Service')], default='normal_product', max_length=20),
        ),
    ]
