# Generated by Django 5.2.7 on 2026-01-14 13:06

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_userprofile_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='base_price',
            new_name='discounted_price',
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='package.jpg', upload_to='package'),
        ),
        migrations.AddField(
            model_name='package',
            name='pacid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=6, max_length=15, prefix='pac_'),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='stock_quantity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='package',
            name='upsell_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PackageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='package.jpg', upload_to='package-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.package')),
            ],
            options={
                'verbose_name_plural': 'Package Images',
            },
        ),
    ]
