# Generated by Django 5.2.7 on 2025-12-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_initial_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='current_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='detected_intent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='greeted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='image_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='interest_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_returning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='language_detected',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_viewed_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='missing_order_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='preferred_tone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='related_products',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
