# Generated by Django 5.2.7 on 2026-01-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_conversation_current_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='current_package',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='current_product',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
