# Generated by Django 5.2.7 on 2026-01-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_conversation_extra_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='back.conversation'),
        ),
    ]
