# Generated by Django 5.2.7 on 2025-12-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_conversation_current_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agent_sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='bot_received_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='bot_sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer_sent_count',
            field=models.IntegerField(default=0),
        ),
    ]
