# Generated by Django 5.2.7 on 2026-01-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_rename_base_price_package_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='action',
            field=models.CharField(choices=[('base', 'Base Included'), ('added', 'Added'), ('removed', 'Removed')], default='base', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='back.package'),
        ),
    ]
