# Generated by Django 5.2.7 on 2025-12-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_conversation_agent_sent_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='customer_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='products'),
        ),
    ]
