# Generated by Django 5.2.7 on 2026-01-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_sale_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='integration_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
