# Generated by Django 5.2.7 on 2025-10-30 12:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_sale_user_alter_product_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivering', 'Delivering'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
