# Generated by Django 5.2.7 on 2025-10-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_sale_user_alter_product_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivering', 'Delivering'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
