# Generated by Django 5.2.7 on 2025-10-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
