# Generated by Django 5.2.7 on 2025-10-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_product_pid_sale_sid_alter_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sid',
        ),
    ]
