# Generated by Django 5.2.7 on 2026-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_integration_integration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
