# Generated by Django 5.2.7 on 2025-10-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
