# Generated by Django 5.2.7 on 2026-01-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_conversation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='profile_image',
            field=models.ImageField(default='customer.jpg', upload_to='customer_profiles'),
        ),
    ]
