# Generated by Django 5.2.7 on 2025-10-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_sale_customer_address_sale_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
