# Generated by Django 5.2.7 on 2026-01-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_conversation_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
