# Generated by Django 5.2.7 on 2026-01-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_alter_conversation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='profile_image',
            field=models.ImageField(blank=True, default='customer.jpg', null=True, upload_to='customer_profiles'),
        ),
    ]
