# Generated by Django 5.2.7 on 2026-01-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_alter_conversation_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
