# Generated by Django 5.2.7 on 2025-12-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_message_attachments_message_mid_message_replied_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
