# Generated by Django 5.2.7 on 2025-10-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_alter_product_options_product_image_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
