# Generated by Django 5.2.7 on 2026-01-30 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_alter_conversation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2026, 1, 30, 19, 23, 37, 862292, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
