# Generated by Django 5.2.7 on 2025-10-30 22:09

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=6, max_length=10, prefix='sku_'),
        ),
    ]
