# Generated by Django 5.1.6 on 2026-02-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_alter_conversation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='current_product',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
