# Generated by Django 5.2.7 on 2025-10-30 22:17

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_product_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=6, max_length=10, prefix='ord_'),
        ),
    ]
