# Generated by Django 5.2.7 on 2025-12-31 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_remove_sale_product_orderitem_external_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='external_variation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_state',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivered_to',
            field=models.CharField(choices=[('inside_dhaka', 'Inside Dhaka'), ('outside_dhaka', 'Outside Dhaka')], default='inside_dhaka', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='back.product'),
        ),
    ]
