# Generated by Django 5.2.7 on 2025-12-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_orderitem_external_variation_id_sale_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='updated_to_web',
            field=models.CharField(choices=[('updated', 'Updated'), ('failed', 'Failed')], default='failed', max_length=20),
        ),
    ]
