# Generated by Django 5.2.7 on 2025-11-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_sale_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
