# Generated by Django 5.1.6 on 2026-02-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_alter_conversation_current_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='current_product',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
