# Generated by Django 5.1.6 on 2026-05-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_alter_conversation_current_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='app_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='verify_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
