# Generated by Django 5.2.7 on 2025-12-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_sale_updated_to_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, default='Unknown Product', max_length=255, null=True),
        ),
    ]
