# Generated by Django 5.2.7 on 2025-11-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_alter_conversation_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ai_enable_delay',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_ai_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
