# Generated by Django 5.2.7 on 2025-12-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='customer_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='refer_customer_with',
            field=models.CharField(default='Sir', max_length=20),
        ),
    ]
