# Generated by Django 5.1.6 on 2026-05-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_integration_ai_model_usagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(default=False, help_text='Featured products are highlighted in store and recommendations'),
        ),
    ]
