# Generated by Django 5.2.7 on 2025-12-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_conversation_customer_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='customer_gender',
        ),
    ]
