# Generated by Django 5.1.6 on 2026-05-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_add_featured_product_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('platform', models.CharField(max_length=20)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversation', 'processed', 'timestamp'], name='back_messag_convers_0b97a0_idx'), models.Index(fields=['processed', 'timestamp'], name='back_messag_process_4c35c2_idx')],
            },
        ),
    ]
