# Generated by Django 5.1.6 on 2026-06-04 10:28

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_messagebatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Product ID in the external store', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('internal', 'Internal (default)'), ('woocommerce', 'WooCommerce'), ('shopify', 'Shopify'), ('external', 'External / Custom')], default='internal', max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('store_url', models.URLField(blank=True, null=True)),
                ('_consumer_key', models.TextField(blank=True, db_column='consumer_key', null=True)),
                ('_consumer_secret', models.TextField(blank=True, db_column='consumer_secret', null=True)),
                ('_api_key', models.TextField(blank=True, db_column='api_key', null=True)),
                ('_access_token', models.TextField(blank=True, db_column='access_token', null=True)),
                ('order_endpoint_url', models.URLField(blank=True, null=True)),
                ('order_endpoint_auth', models.JSONField(blank=True, help_text='Optional extra headers/auth for custom order endpoint', null=True)),
                ('mode', models.CharField(choices=[('sync', 'Synced cache'), ('live', 'Live fetch')], default='sync', max_length=10)),
                ('is_active', models.BooleanField(default=False, help_text='The single active source the AI reads from')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='disconnected', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=6, max_length=15, prefix='src_')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Sources',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Null = internal/default product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='back.productsource'),
        ),
    ]
