# Generated by Django 5.2.7 on 2025-12-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_remove_conversation_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='customer_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Unknown', 'unknown')], default='unknown', max_length=20),
        ),
    ]
