# Generated by Django 5.1.6 on 2026-06-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_product_external_id_productsource_product_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='connection_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('oauth', 'OAuth')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='integration',
            name='ig_account_id',
            field=models.CharField(blank=True, help_text='Linked Instagram business account id', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='meta_user_id',
            field=models.CharField(blank=True, help_text='FB user id who connected (for token refresh)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='page_name',
            field=models.CharField(blank=True, help_text='Connected Meta Page name (OAuth)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Long-lived token expiry', null=True),
        ),
    ]
