# Generated by Django 5.1.6 on 2026-06-15 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back", "0020_supportticket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ToolCallLog",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "reply_id",
                            models.CharField(db_index=True, max_length=255),
                        ),
                        ("iteration", models.IntegerField()),
                        (
                            "tool_name",
                            models.CharField(db_index=True, max_length=100),
                        ),
                        ("arguments", models.JSONField()),
                        ("result_summary", models.TextField()),
                        ("execution_time_ms", models.IntegerField()),
                        (
                            "timestamp",
                            models.DateTimeField(auto_now_add=True),
                        ),
                        (
                            "conversation",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="back.conversation",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Tool Call Log",
                        "verbose_name_plural": "Tool Call Logs",
                        "ordering": ["-timestamp"],
                        "indexes": [
                            models.Index(
                                fields=["conversation", "timestamp"],
                                name="back_toolca_convers_356644_idx",
                            )
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE back_toolcalllog "
                "DROP CONSTRAINT IF EXISTS back_toolcalllog_conversation_id_13331510_fk_back_conv, "
                "ADD CONSTRAINT back_toolcalllog_conversation_id_13331510_fk_back_conv "
                "FOREIGN KEY (conversation_id) REFERENCES back_conversation(id) "
                "ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
