# Generated by Django 5.1.6 on 2026-07-31 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_alter_toolcalllog_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result_state', models.CharField(default='success', max_length=20)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('actor_role', models.CharField(blank=True, default='', max_length=50)),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'tool_name', 'timestamp'], name='back_auditl_user_id_e1ac7a_idx')],
            },
        ),
    ]
