# Generated by Django 5.1.6 on 2026-07-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0023_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='customer_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
