# Generated by Django 5.1.6 on 2026-08-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0025_backfill_toolcalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcalllog',
            name='conversation_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='toolcalllog',
            name='intent_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolcalllog',
            name='plan_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolcalllog',
            name='plan_goal',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
