# Generated by Django 5.1.6 on 2026-08-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0026_toolcalllog_conversation_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
