# Generated by Django 5.1.6 on 2026-09-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0027_userprofile_setup_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_training',
            field=models.BooleanField(default=False),
        ),
    ]
