# Generated by Django 5.1.6 on 2026-09-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0028_userprofile_is_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='sent', max_length=20),
        ),
    ]
