# Generated by Django 5.1.6 on 2026-09-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0029_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='incoming_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
