# Generated by Django 5.1.6 on 2026-08-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_learningtopic_learningarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook'), ('messenger', 'Messenger'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('manual', 'Manual'), ('referral', 'Referral'), ('import', 'Import')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesscript',
            name='category',
            field=models.CharField(choices=[('cold_call', 'Cold Call'), ('followup', 'Follow-up'), ('objection', 'Objection Handling'), ('demo', 'Demo'), ('closing', 'Closing'), ('renewal', 'Renewal'), ('upsell', 'Upsell'), ('lost_customer', 'Winning Back Lost Customer'), ('texts', 'Texts')], default='cold_call', max_length=20),
        ),
    ]
