# Generated by Django 5.1.6 on 2026-08-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_lead_source_alter_salesscript_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='score_value',
            field=models.PositiveSmallIntegerField(default=0, help_text='Score contribution when a lead reaches this stage (auto lead scoring)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('call', 'Call'), ('demo', 'Demo'), ('email', 'Email'), ('meeting', 'Meeting'), ('assignment', 'Assignment'), ('status_change', 'Status Change'), ('proposal', 'Proposal'), ('won', 'Deal Won'), ('lost', 'Deal Lost'), ('created', 'Lead Created'), ('onboarding', 'Onboarding'), ('score', 'Score Change')], default='note', max_length=20),
        ),
    ]
