# Generated by Django 5.1.6 on 2026-08-30 03:39

import django.db.models.deletion
import django_ckeditor_5.fields
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_score_breakdown_pipelinestage_score_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=12, max_length=16, prefix='emb_')),
                ('subject_rendered', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Null = send immediately', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_email_batches_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_tenant_email_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=12, max_length=16, prefix='etp_')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(help_text='Supports tokens: {{lead.name}}, {{lead.email}}, etc.', max_length=200)),
                ('body_html', django_ckeditor_5.fields.CKEditor5Field(help_text='Rich text editor. Tokens will be replaced at send time.')),
                ('body_text', models.TextField(blank=True, default='', help_text='Plain-text fallback (auto-generated from HTML if empty)')),
                ('category', models.CharField(choices=[('cold', 'Cold Outreach'), ('followup', 'Follow-up'), ('nurture', 'Nurture'), ('proposal', 'Proposal'), ('announcement', 'Announcement')], default='cold', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_email_templates_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null = internal MatrixAI template (available to all). Set for per-tenant templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_tenant_email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=12, max_length=16, prefix='eml_')),
                ('recipient_email', models.EmailField(help_text='Frozen at send time', max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField(help_text='Rendered body for debugging/audit')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='crm.emailbatch')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_logs', to='crm.lead')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='crm.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='crm.emailtemplate'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_emailte_tenant__7903cb_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['batch', 'status'], name='crm_emaillo_batch_i_97461c_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['lead', 'status'], name='crm_emaillo_lead_id_02df23_idx'),
        ),
        migrations.AddIndex(
            model_name='emailbatch',
            index=models.Index(fields=['tenant', 'status'], name='crm_emailba_tenant__edeb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailbatch',
            index=models.Index(fields=['tenant', 'scheduled_at'], name='crm_emailba_tenant__3e54a2_idx'),
        ),
    ]
