# Generated by Django 5.1.6 on 2026-09-01 20:41

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_emailbatch_emailtemplate_emaillog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=12, max_length=16, prefix='ema_')),
                ('email', models.EmailField(max_length=254)),
                ('provider', models.CharField(choices=[('smtp', 'SMTP'), ('google', 'Google Workspace'), ('microsoft', 'Microsoft 365')], default='smtp', max_length=20)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=200)),
                ('smtp_password', models.CharField(blank=True, default='', help_text='Encrypted in production', max_length=300)),
                ('use_tls', models.BooleanField(default=True)),
                ('daily_limit', models.PositiveIntegerField(default=50)),
                ('sent_today', models.PositiveIntegerField(default=0)),
                ('last_sent_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reputation', models.CharField(choices=[('good', 'Good'), ('warm', 'Warm'), ('poor', 'Poor')], default='good', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_email_accounts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_tenant_email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=12, max_length=16, prefix='cmp_')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Internal reference')),
                ('campaign_type', models.CharField(choices=[('one_time', 'One-time Campaign'), ('sequence', 'Email Sequence')], default='one_time', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('daily_limit', models.PositiveIntegerField(default=50)),
                ('min_interval', models.PositiveIntegerField(default=2, help_text='Minimum minutes between sends')),
                ('max_interval', models.PositiveIntegerField(default=5, help_text='Maximum minutes between sends')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Null = send immediately', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('bounced_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('replied_count', models.PositiveIntegerField(default=0)),
                ('ai_personalization', models.BooleanField(default=False)),
                ('ai_instruction', models.TextField(blank=True, default='')),
                ('ai_tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('direct', 'Direct'), ('casual', 'Casual')], default='friendly', max_length=20)),
                ('personalization_fields', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=dict, help_text='stop_on_reply, skip_bounced, skip_contacted, etc.')),
                ('audience_type', models.CharField(choices=[('segment', 'Existing Segment'), ('filter', 'Filter Leads'), ('manual', 'Select Manually')], default='manual', max_length=20)),
                ('audience_data', models.JSONField(blank=True, default=dict, help_text='Filter criteria or selected lead IDs')),
                ('rq_job_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='crm.emailtemplate')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_tenant_campaigns', to=settings.AUTH_USER_MODEL)),
                ('sending_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='crm.emailaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=12, max_length=16, prefix='cpl_')),
                ('email_snapshot', models.EmailField(blank=True, default='', help_text='Frozen at send time', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('replied', 'Replied')], default='pending', max_length=20)),
                ('subject_rendered', models.CharField(blank=True, default='', max_length=200)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Campaign Lead',
                'verbose_name_plural': 'Campaign Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='crm_campaig_campaig_135a7d_idx'), models.Index(fields=['lead', 'status'], name='crm_campaig_lead_id_42d29f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'status'], name='crm_campaig_tenant__f09ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'scheduled_at'], name='crm_campaig_tenant__be3692_idx'),
        ),
    ]
