"""
Django settings for theMatrixAi project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from environ import Env

env = Env()
Env.read_env()

ENVIROMNENT = env("ENVIROMNENT", default="development")
POSTGRES_LOCALLY  = env.bool('POSTGRES_LOCALLY ', default=False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Updated BASE_DIR definition to use os.path
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-!$#k@v1z&2e3g4h5i6j7k8l9m0n1o2p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7e8f9g0")
ENCRYPT_KEY = env("ENCRYPT_KEY", default="default_encrypt_key_please_change_me_1234567890")
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
# The Orchestrator is the ONLY AI path (webhooks always route through it).
# The flag is kept for compatibility; it defaults to True.
AI_ORCHESTRATOR_ENABLED = os.environ.get("AI_ORCHESTRATOR_ENABLED", "True") == "True"

# --- Meta (Facebook/Instagram) OAuth + app-level webhook ---
META_APP_ID = env("META_APP_ID", default="")
META_APP_SECRET = env("META_APP_SECRET", default="")
META_WEBHOOK_VERIFY_TOKEN = env("META_WEBHOOK_VERIFY_TOKEN", default="")
META_GRAPH_VERSION = env("META_GRAPH_VERSION", default="v23.0")
# Space-separated OAuth scopes requested during Connect-with-Facebook.
META_OAUTH_SCOPES = env(
    "META_OAUTH_SCOPES",
    default="pages_show_list,pages_messaging,pages_manage_metadata,pages_manage_engagement,pages_read_engagement,pages_read_user_content,pages_manage_posts,business_management,instagram_basic,instagram_manage_messages,instagram_manage_comments,public_profile,email",
)
# Optional explicit redirect URI override (else built from the request).
META_OAUTH_REDIRECT_URI = env("META_OAUTH_REDIRECT_URI", default="")

# --- Meta Pixel (marketing analytics) ---
# Empty/absent disables the pixel entirely.
META_PIXEL_ID = env("META_PIXEL_ID", default="")

# SECURITY WARNING: don't run with debug turned on in production!

if ENVIROMNENT == "development":
    DEBUG = True
else:
    DEBUG = False

if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


ALLOWED_HOSTS = ['*']

# Trust X-Forwarded-Proto from Railway so Django knows requests are HTTPS.
# Without this, build_absolute_uri() produces http:// URLs which Meta rejects.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = [
    "https://matrix-production-867a.up.railway.app",
    "http://matrix-production-867a.up.railway.app",
    "https://thematrixai.xyz",
    "http://thematrixai.xyz",
    "https://www.thematrixai.xyz",
    "http://www.thematrixai.xyz",
]



# Application definition

INSTALLED_APPS = [
    "front",
    "back",
    "api",
    "rest_framework",
    "msg",
    "context",
    "billing",
    "blog",
    "crm",
    "hiring",

    "django_ckeditor_5",
    "django.contrib.sitemaps",
    "django.contrib.syndication",

    "shortuuid",
    # "mysql",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "crm.permissions.CrmStaffGuardMiddleware",
]

ROOT_URLCONF = "theMatrixAi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "back.context_processors.integration_status",
                "back.context_processors.meta_pixel",
            ],
        },
    },
]

WSGI_APPLICATION = "theMatrixAi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Example environment flags
ENVIRONMENT = os.environ.get("ENVIRONMENT", "development")
POSTGRES_LOCALLY = os.environ.get("POSTGRES_LOCALLY", "False") == "True"

# Default SQLite configuration
if ENVIRONMENT == "production" or POSTGRES_LOCALLY:
    print("Using Postgres Database")
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL"))
    }
else:
    print("Using SQLite Database")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Keep database connections alive for 60s to avoid per-request TCP handshake
DATABASES["default"]["CONN_MAX_AGE"] = 60

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dhaka"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # where your "front/main.css" lives
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# --------------------
# MEDIA FILES
# --------------------





# USE_FTP = os.environ.get("USE_FTP", "false").lower() == "true"

# if USE_FTP:
#     print("Using FTP Storage for media files")
#     DEFAULT_FILE_STORAGE = "back.ftp_storage.FTPStorage"
#     MEDIA_URL = os.environ.get("FTP_BASE_URL")
#     MEDIA_ROOT = ""        # Not used locally
#     print("MEDIA_URL:", MEDIA_URL)
#     print("MEDIA_ROOT:", MEDIA_ROOT)

# else:
#     print("Using Local Storage for media files")
#     MEDIA_URL = "/media/"
#     MEDIA_ROOT = BASE_DIR / "media"



IS_PRODUCTION = ENVIRONMENT == "production"

CLOUDFLARE_R2_BUCKET = os.environ.get("CLOUDFLARE_R2_BUCKET")
CLOUDFLARE_R2_ACCESS_KEY = os.environ.get("CLOUDFLARE_R2_ACCESS_KEY")
CLOUDFLARE_R2_SECRET_KEY = os.environ.get("CLOUDFLARE_R2_SECRET_KEY")
CLOUDFLARE_R2_BUCKET_ENDPOINT = os.environ.get("CLOUDFLARE_R2_BUCKET_ENDPOINT")
AWS_S3_CUSTOM_DOMAIN = os.environ.get("CLOUDFLARE_R2_PUBLIC_DOMAIN")

CLOUDFLARE_R2_CONFIG_OPTIONS = {
    "bucket_name": CLOUDFLARE_R2_BUCKET,
    "access_key": CLOUDFLARE_R2_ACCESS_KEY,
    "secret_key": CLOUDFLARE_R2_SECRET_KEY,
    "endpoint_url": CLOUDFLARE_R2_BUCKET_ENDPOINT,
    "default_acl": "public-read",
    "signature_version": "s3v4",
}

# Use Cloudflare R2 whenever the bucket config is present (dev + production).
# This guarantees every image/file save lands in R2 and default_storage.url()
# returns the absolute public CDN URL — required for Messenger/WhatsApp sends.
if CLOUDFLARE_R2_BUCKET and CLOUDFLARE_R2_ACCESS_KEY and CLOUDFLARE_R2_SECRET_KEY and CLOUDFLARE_R2_BUCKET_ENDPOINT:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS,
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS,
        },
    }
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
    STATIC_URL = "/static/"

# Working
# https://pub-421b25bbb74c448fa8ac1458aa3f57f7.r2.dev/products/maxresdefault.jpg

# https://https//pub-421b25bbb74c448fa8ac1458aa3f57f7.r2.dev/products/maxresdefault.jpg


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_URL = 'front:login'

# --------------------
# EMAIL (optional — enabled only when SMTP env vars are set)
# --------------------
if os.environ.get("EMAIL_HOST"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER) or "noreply@thematrixai.xyz"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "noreply@thematrixai.xyz"


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.TokenAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }

# --------------------
# CKEDITOR 5 CONFIGURATION
# --------------------
CKEDITOR_5_UPLOAD_FILE_TYPES = ["jpg", "jpeg", "png", "gif", "bmp", "webp", "tiff", "svg", "avif"]

CKEDITOR_5_CONFIGS = {
    "blog": {
        "toolbar": [
            "heading", "|", "bold", "italic", "underline", "strikethrough",
            "link", "|",
            "bulletedList", "numberedList", "blockQuote", "insertTable",
            "|", "codeBlock", "code", "|",
            "imageUpload", "mediaEmbed", "horizontalLine",
            "|", "undo", "redo", "sourceEditing"
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative", "imageStyle:full", "imageStyle:side",
                "linkImage"
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn", "tableRow", "mergeTableCells",
                "tableProperties", "tableCellProperties"
            ],
        },
        "heading": {
            "options": [
                {"model": "paragraph", "title": "Paragraph", "class": "ck-heading_paragraph"},
                {"model": "heading2", "view": "h2", "title": "Heading 2", "class": "ck-heading_heading2"},
                {"model": "heading3", "view": "h3", "title": "Heading 3", "class": "ck-heading_heading3"},
                {"model": "heading4", "view": "h4", "title": "Heading 4", "class": "ck-heading_heading4"},
                {"model": "heading5", "view": "h5", "title": "Heading 5", "class": "ck-heading_heading5"},
                {"model": "heading6", "view": "h6", "title": "Heading 6", "class": "ck-heading_heading6"},
            ],
        },
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True,
            }
        },
        "htmlSupport": {
            "allow": [
                {"name": "/.*/", "attributes": True, "classes": True, "styles": True}
            ]
        },
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "api": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "back": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "billing": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "context": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
