"""
Django settings for theMatrixAi project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from environ import Env

env = Env()
Env.read_env()

ENVIROMNENT = env("ENVIROMNENT", default="development")
POSTGRES_LOCALLY  = env.bool('POSTGRES_LOCALLY ', default=False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Updated BASE_DIR definition to use os.path
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-!$#k@v1z&2e3g4h5i6j7k8l9m0n1o2p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7e8f9g0")
ENCRYPT_KEY = env("ENCRYPT_KEY", default="default_encrypt_key_please_change_me_1234567890")

# SECURITY WARNING: don't run with debug turned on in production!

if ENVIROMNENT == "development":
    DEBUG = True
else:
    DEBUG = False

if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "https://matrix-production-867a.up.railway.app",
    "http://matrix-production-867a.up.railway.app",
    "https://thematrixai.xyz",
    "http://thematrixai.xyz"
]



# Application definition

INSTALLED_APPS = [
    "front",
    "back",
    "api",
    "rest_framework",
    "msg",

    "shortuuid",
    
    # "rest_framework.authtoken",
    # "mysql",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "theMatrixAi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "theMatrixAi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Example environment flags
ENVIRONMENT = os.environ.get("ENVIRONMENT", "development")
POSTGRES_LOCALLY = os.environ.get("POSTGRES_LOCALLY", "False") == "True"

# Default SQLite configuration
if ENVIRONMENT == "production" or POSTGRES_LOCALLY:
    print("Using Postgres Database")
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL"))
    }
else:
    print("Using SQLite Database")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # where your "front/main.css" lives
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# --------------------
# MEDIA FILES
# --------------------





# USE_FTP = os.environ.get("USE_FTP", "false").lower() == "true"

# if USE_FTP:
#     print("Using FTP Storage for media files")
#     DEFAULT_FILE_STORAGE = "back.ftp_storage.FTPStorage"
#     MEDIA_URL = os.environ.get("FTP_BASE_URL")
#     MEDIA_ROOT = ""        # Not used locally
#     print("MEDIA_URL:", MEDIA_URL)
#     print("MEDIA_ROOT:", MEDIA_ROOT)

# else:
#     print("Using Local Storage for media files")
#     MEDIA_URL = "/media/"
#     MEDIA_ROOT = BASE_DIR / "media"



# In production, MEDIA_ROOT should point to the mounted volume path
# In development, it can point to a local 'media' folder

# Detect Railway environment

if os.environ.get("MOUNT_MEDIA"):
    MEDIA_ROOT = "/app/media"
    print("Using Railway mounted volume for MEDIA_ROOT")
    print(MEDIA_ROOT)
    print("Files in MEDIA_ROOT:")
    # print(os.listdir(MEDIA_ROOT))

    # product_dir = os.path.join(MEDIA_ROOT, "products")
    # if os.path.exists(product_dir):
    #     print("Files in products/:")
    #     print(os.listdir(product_dir))
    # else:
    #     print("products/ directory does not exist")

else:
    MEDIA_ROOT = BASE_DIR / "media"
    print("Using local folder for MEDIA_ROOT")
    print(MEDIA_ROOT)
    print("Using LocalHost mounted volume for MEDIA_ROOT")
    print(MEDIA_ROOT)
    print("Files in MEDIA_ROOT:")
    print(os.listdir(MEDIA_ROOT))

    product_dir = os.path.join(MEDIA_ROOT, "products")
    if os.path.exists(product_dir):
        print("Files in products/:")
        print(os.listdir(product_dir))
    else:
        print("products/ directory does not exist")

MEDIA_URL = "/media/data/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_URL = 'front:login'


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.TokenAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }
