# Generated by Django 5.2.7 on 2025-12-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatTransferProtocol',
        ),
    ]
