# Generated by Django 5.1.6 on 2026-08-03 07:09

import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('offline', 'Offline / In-person')], default='zoom', max_length=20)),
                ('link', models.URLField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=10, max_length=14, prefix='can_')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('position', models.CharField(choices=[('sales_staff', 'Sales Staff'), ('sales_executive', 'Sales Executive'), ('sales_manager', 'Sales Manager'), ('support', 'Support')], default='sales_staff', max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('skills', models.TextField(blank=True, default='', help_text='Comma-separated list of skills')),
                ('expected_salary', models.CharField(blank=True, default='', max_length=60)),
                ('availability', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hiring/photos/%Y/%m/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='hiring/cv/%Y/%m/')),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social', 'Social Media'), ('manual', 'Manual Entry')], default='website', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hired_user', models.OneToOneField(blank=True, help_text='CRM account created on hire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_candidate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp', models.CharField(choices=[('invited', 'Invited'), ('attended', 'Attended'), ('no_show', 'No Show')], default='invited', max_length=10)),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='hiring.candidateapplication')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='hiring.hiringmeeting')),
            ],
        ),
        migrations.AddIndex(
            model_name='candidateapplication',
            index=models.Index(fields=['status'], name='hiring_cand_status_60584e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateapplication',
            index=models.Index(fields=['email'], name='hiring_cand_email_4c17a6_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateapplication',
            index=models.Index(fields=['phone'], name='hiring_cand_phone_623bc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendee',
            unique_together={('meeting', 'candidate')},
        ),
    ]
