# Generated by Django 5.1.6 on 2026-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplication',
            name='_temp_password',
            field=models.TextField(blank=True, db_column='temp_password', null=True),
        ),
    ]
